server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:searchDb
    username: search

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

src-api:
  kakao:
    host: https://dapi.kakao.com
    rest-api:
      key: Authorization
      value: KakaoAK 9b020a52082c0da8b0dd38fd2caa52f7
  naver:
    host: https://openapi.naver.com
    client-id:
      key: X-Naver-Client-Id
      value: clb8tZ4w_oEG3pY_CdCt
    client-secret:
      key: X-Naver-Client-Secret
      value: bvFCWtbcwq

